name: CI Pipeline

on:
  push: 
    branches: ["main", "dev"]
  pull_request:
    branches: ["main"]

jobs:
  # Job 1: Lint PowerShell scripts
  lint-powershell:
    name: Lint PowerShell (PSScriptAnalyzer)
    runs-on: windows-latest

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4 # Use an Action meaning "Download the repo in the VM" -> Downloads my repo in Git

      - name: Install PSScriptAnalyzer
        shell: pwsh # Choose the type of shell to run the command (pwsh - powershell)
        run: Install-Module -Name PSScriptAnalyzer -Scope CurrentUser -Force # The command used for the shell

      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          # Analyze all PowerShell scripts in deploy/ folder
          # Exclude PSAvoidUsingWriteHost — intentionally used for colored console output
          $results = Invoke-ScriptAnalyzer -Path ./deploy -Recurse` 
            -ExcludeRule PSAvoidUsingWriteHost, PSAvoidTrailingWhitespace 
        
          if ($results) {
            $results | Format-Table -AutoSize
            Write-Host "PSScriptAnalyzer found $($results.Count) issue(s)." -ForegroundColor Red
            exit 1
          } else {
              Write-Host "PSScriptAnalyzer: No issues found." -ForegroundColor Green
          }

  # Job 2: Lint Python code
  lint-python:
    name: Lint Python (flake8)
    runs-on: ubuntu-latest

    steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.11"

        - name: Install flake8
          run: pip install flake8

        - name: Run flake8
          run: |
            # E501: ignore line too long (max 120 chars for readability)
            # W503: ignore line break before binary operator
            flake8 validate/ tests/ \
              --max-line-length=120 \
              --extend-ignore=E501,W503

  # Job 3: Run unit tests
  test-python:
      name: Unit Tests (pytest)
      runs-on: ubuntu-latest
      needs: lint-python
      # Only run tests if linting passed

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.11"

        - name: Install dependencies
          run: pip install -r validate/requirements.txt pytest

        - name: Run pytest
          run: python -m pytest tests/ -v
